#$ conda env create --file conda-env.yaml
name: deepslide_env
channels:
  - pytorch
  - nvidia 
  - conda-forge
dependencies:
  - python=3.11
  - torchvision
  - pytorch-cuda=11.7
  - pytorch
  - pandas
  - matplotlib
  - scikit-learn
  - scikit-image
  - pip
  - pip:
    - -r pip-requirements.txt
