#$ conda env create --file conda-env.yaml
name: deepslide_env
channels:
dependencies:
  - python=3.9
  - conda-forge::torchvision=0.15.2
  - nvidia::cudatoolkit=11.7.0
  - conda-forge::pytorch-gpu=2.0.0
  - pandas
  - matplotlib
  - scikit-learn
  - scikit-image
  - pip
  - pip:
    - -r pip-requirements.txt
